name: .NET Core Desktop

on:
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to the main branch

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]  # Run on both Debug and Release configurations

    runs-on: windows-latest  # Use a Windows runner for .NET Core

    env:
      Solution_Name: BackEnd/BackEnd.sln  # Path to your .sln file
      Test_Project_Path: BackEnd/BackEnd.Tests/BackEnd.Tests.csproj  # Path to your test project

    steps:
      # 1. Checkout the source code from the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure the entire repo history is fetched

      # 2. Install .NET Core
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x  # Make sure you are using the correct .NET Core version

      # 3. Install MSBuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      # 4. Restore project dependencies
      - name: Restore dependencies
        run: dotnet restore ${{ env.Solution_Name }}

      # 5. Build the solution (to check for compilation errors)
      - name: Build solution
        run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}

      # 6. Execute unit tests
      - name: Execute .NET unit tests
        run: dotnet test ${{ env.Test_Project_Path }} --configuration ${{ matrix.configuration }}

      # 7. Restore the application (if needed)
      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}
